// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWezcmuESVvg4vwzJ1pRwBsRDfxey-YMA',
    appId: '1:1011820134821:web:ed3ba7ff59657cbadc284c',
    messagingSenderId: '1011820134821',
    projectId: 'todo-app-a62e7',
    authDomain: 'todo-app-a62e7.firebaseapp.com',
    storageBucket: 'todo-app-a62e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGlpY_s2pseUb5Wyhg5-s_MOO2jyVR1nY',
    appId: '1:1011820134821:android:0fafcf93e36ab620dc284c',
    messagingSenderId: '1011820134821',
    projectId: 'todo-app-a62e7',
    storageBucket: 'todo-app-a62e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4E6y6Wrkk3gKf07LoN5-7bSqv1G_HmgA',
    appId: '1:1011820134821:ios:b77afa48f5a91293dc284c',
    messagingSenderId: '1011820134821',
    projectId: 'todo-app-a62e7',
    storageBucket: 'todo-app-a62e7.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4E6y6Wrkk3gKf07LoN5-7bSqv1G_HmgA',
    appId: '1:1011820134821:ios:b77afa48f5a91293dc284c',
    messagingSenderId: '1011820134821',
    projectId: 'todo-app-a62e7',
    storageBucket: 'todo-app-a62e7.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );
}
